# Generated by Django 2.1.7 on 2019-03-10 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('hash', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=75, null=True)),
                ('registerDate', models.DateField(default=datetime.date(2019, 3, 10))),
            ],
        ),
    ]
